config:
  # The chart now always deploys 1 replica.
  server_name: "your.server.name"
  new_user_displayname_suffix: ""
  max_request_size: "20971520"
  allow_registration: true
  allow_federation: true
  trusted_servers: []

image:
  repository: ghcr.io/girlbossceo/conduwuit
  tag: "main"
  pullPolicy: Always

extraConfig: ""

extraEnv: []

## Add additional labels to all resources
extraLabels: {}

service:
  annotations: {}
  type: ClusterIP
  clusterIP: "None"

  port: 80
  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

ingress:
  enabled: false
  class: ""
  # You will probably want to provide either large upload size limits, or no
  #    upload size limit; for example, if using nginx-ingress, include
  #    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  annotations: {}
  path: /
  hostname: ""
  tls: false

## Persist configuration to a persistent volume
persistence:
  ## Data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If unset, storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  data:
    enabled: true
    existingClaim:
    storageClass:
    accessMode: ReadWriteOnce
    size: 8Gi

resources:
  requests:
    cpu: "2"
    memory: "512Mi"
  limits:
    memory: "1024Mi"

nodeSelector: {}

tolerations: []

affinity: {}
