{{- if .Values.ingress.enabled -}}
{{- $fullName := include "conduwuit.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "conduwuit.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.class }}
  ingressClassName: {{ tpl . $ }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ tpl (.Values.ingress.hostname) $ | default (printf "matrix.%s" .Values.config.server_name) }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    - host: {{ tpl (.Values.ingress.hostname) $ | default (printf "matrix.%s" .Values.config.server_name) }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
    - host: {{ .Values.config.server_name }}
      http:
        paths:
          - path: /.well-known/matrix/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
{{- end }}
